version: "3.1"
services:
  nginx:
        image: nginx:1.13.7
        container_name: nginx
        depends_on:
            - app_1
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app_net
        ports:
            - 80:80
  app_1:
    image: certainnathan/micro-app-1-bbk:latest
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 2
    networks:
      app_net:
         aliases:
            - app_1
  app_2:
    image: certainnathan/micro-app-2-bbk:latest
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 6
    networks:
      - app_net
  app_3:
    image: certainnathan/micro-app-3-bbk:latest
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 6
    networks:
      - app_net
  app_4:
    image: certainnathan/micro-app-4-bbk:latest
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 2
    networks:
      - app_net
networks:
  app_net:
    driver: overlay
